### ISSUE TITLE
[BUG-HA]  ESPHome 2025.10.3 breaks UART comms (spams the bus with 0x00)

### ISSUE THREAD

**Issue by ouaibe** [ouaibe/dreo-cloudcutter#12]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Is this question already covered by the FAQ?

- [x] I have read the FAQ.

### Your Fan Model (ONLY the DR-HTF004S is supported at the moment).

DR-HTF004S

### ESPHome's version.

2025.10.3

### Your Fan MCU Version.

1

### Current Behavior & Error logs.

ESPHome 2025.10.3 has some issue with the UART readout from the MCU and spams 0x00 messages in the logger that allows to process the MCU commands back and forth.

This crashes the ESPHome device after some time:

`[15:34:31.959][D][uart_debug:158]: <<< "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x [15:34:31.970][D][main:256]: Unknown UART Command received from MCU [15:34:31.973][D][main:258]: 0x00 [15:34:31.977][D][main:258]: 0x00 [15:34:31.981][D][main:258]: 0x00 [15:34:31.981][D][main:258]: 0x00 [15:34:31.985][D][main:258]: 0x00 [15:34:31.989][D][main:258]: 0x00 [15:34:31.992][D][main:258]: 0x00 [15:34:31.996][D][main:258]: 0x00 [15:34:31.998][D][main:258]: 0x00 [15:34:32.002][D][main:258]: 0x00 [15:34:32.003][D][main:258]: 0x00 [15:34:32.006][D][main:258]: 0x00 [15:34:32.009][D][main:258]: 0x00 [15:34:32.013][D][main:258]: 0x00 [15:34:32.015][D][main:258]: 0x00 [15:34:32.019][D][main:258]: 0x00 [15:34:32.022][D][main:258]: 0x00 [15:34:32.026][D][main:258]: 0x00 [15:34:32.028][D][main:258]: 0x00 [15:34:32.033][D][main:258]: 0x00 [15:34:32.037][D][main:258]: 0x00 [15:34:32.043][D][main:258]: 0x00 [15:34:32.043][D][main:258]: 0x00 [15:34:32.045][D][main:258]: 0x00 [15:34:32.049][D][main:258]: 0x00 [15:34:32.053][D][main:258]: 0x00 [15:34:32.056][D][main:258]: 0x00 [15:34:32.060][D][main:258]: 0x00 [15:34:32.063][D][main:258]: 0x00 [15:34:32.067][D][main:258]: 0x00 [15:34:32.070][D][main:258]: 0x00 [15:34:32.072][D][main:258]: 0x00 [15:34:32.076][D][main:258]: 0x00 [15:34:32.080][D][main:258]: 0x00 [15:34:32.083][D][main:258]: 0x00 [15:34:32.084][D][main:258]: 0x00 [15:34:32.088][D][main:258]: 0x00 [15:34:32.092][D][main:258]: 0x00 [15:34:32.098][D][main:258]: 0x00 [15:34:32.098][D][main:258]: 0x00 [15:34:32.100][D][main:258]: 0x00 [15:34:32.104][D][main:258]: 0x00 [15:34:32.108][D][main:258]: 0x00 [15:34:32.111][D][main:258]: 0x00 `

I was able to confirm that 2025.5, 2025.6, 2025.7 and 2025.9 are NOT affected by this issue.

2025.10 seems the only version affected by this, and coincidentally this change looks very related: https://github.com/esphome/esphome/pull/9248 (reported as potentially breaking libretiny https://github.com/esphome/esphome/issues/11513)

I don't have a workaround yet.

Do NOT update past 2025.9 - You can use https://github.com/khenderick/esphome-legacy-addons to install a specific version of ESPHome.

### Expected Behavior.

Should work flawlessly.

### Steps To Reproduce, including errors you've seen.

Update to 2025.10 WILL BREAK the integration.

### Information about your browser environment.

- Browser:
- Version:

**Comment by aebgit** [comment]
I can confirm this worked up to and including ESPHome `2025.10.2` . 
With ESPHome `2025.10.3` the `0x00` issue was introduced and the fan can no longer be operated.
Rolling back to `2025.10.2` from backup and cleaning + re-building the integration worked.

**Comment by ouaibe** [comment]
Seems like https://github.com/esphome/esphome/pull/11518 might solve this.

Will wait for an official ESPHome version release to test it.

**Comment by ouaibe** [comment]
[2025.10.4](https://esphome.io/changelog/2025.10.0) has been released and contains https://github.com/esphome/esphome/pull/11518 that should fix the UART bug if someone wants to validate it.

**Comment by aebgit** [comment]
Just built it under `2025.10.4` and can confirm it works again.

**Comment by nununo** [comment]
I upgraded one of my ACs to 2025.10.4 and the issue is still there:

```
16:52:07 | [W] | [CN105:325] | Heatpump has not replied for 7245 s
16:52:07 | [I] | [CN105:326] | We think Heatpump is not connected anymore..
16:52:07 | [I] | [CN105:355] | Forcing low-level UART reinit on port 0 (tx=17, rx=16)
16:52:07 | [I] | [CN105:009] | setupUART() with baudrate  2400
```

This was working fine before.

**Comment by ouaibe** [comment]
> I upgraded one of my ACs to 2025.10.4 and the issue is still there:
> 
> ```
> 16:52:07 | [W] | [CN105:325] | Heatpump has not replied for 7245 s
> 16:52:07 | [I] | [CN105:326] | We think Heatpump is not connected anymore..
> 16:52:07 | [I] | [CN105:355] | Forcing low-level UART reinit on port 0 (tx=17, rx=16)
> 16:52:07 | [I] | [CN105:009] | setupUART() with baudrate  2400
> ```
> 
> This was working fine before.

Thanks, but you want to bring that discussion to https://github.com/esphome/esphome/pull/11518 and/or another ticket in ESPhome, not in here, as this is ESPhome issue, NOT, related to this repo (which is only concerned with Dreo fans running ESPhome).

**Comment by nununo** [comment]
Understood, sorry.

**Comment by ouaibe** [comment]
Tested 2025.11.3 and 2025.11.4 without any noticeable issues, changed a few fan settings post-update and everything seems to be running smoothly.

Note to all, it's always better to wait a few releases before hopping on the latest ESPHome: it is not the first time (nor I suspect the last) that there are major breakeages like this with very new releases.

I'll close this issue as resoved.
